- hosts: terraform-ansible
  tasks:
  - name: Instalando o Python3 e o Virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes

  - name: Git clone do repositório
    ansible.builtin.git:
     repo: https://github.com/guilhermeonrails/clientes-leo-api.git
     dest: /home/ubuntu/tcc
     version: master  #Esta é a branch que você quer clonar
     force: yes # Força a atualização do repositório se já existir

  - name: Instalando dependencias com pip (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      requirements: /home/ubuntu/tcc/requirements.txt
  
  - name: Configurando hosts de settings.py com Ansible
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes

  - name: Instalar setuptools #remenda a ausência do pacote distutils
    pip:
      name: setuptools
      virtualenv: /home/ubuntu/tcc/venv

  - name: Configurando o banco de dados com Ansible
    shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py migrate'

  - name: Carregando os dados iniciais com Ansible
    shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py loaddata clientes.json'
  - name: Iniciando o servidor Django
    shell: '. /home/ubuntu/tcc/venv/bin/activate; nohup python /home/ubuntu/tcc/manage.py runserver 0.0.0.0:8000 &'