- hosts: terraform-ansible
  tasks:
  - name: Instalando o Python3 e o Virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
    
  - name: Instalando dependencias com pip (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/venv
      name:
        - django
        - djangorestframework
  - name: Verificando se o projeto já existe
    stat:
      path: /home/ubuntu/setup/settings.py #se existe o arquivo -> projeto já foi criado
    register: projeto # se true -> existe o projeto
  
  - name: Iniciando o Projeto
    shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/'
    when: not projeto.stat.exists # se o projeto existe, pula-se essa task
  
  - name: Configurando um arquivo com Ansible
    lineinfile:
      path: /home/ubuntu/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes